version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: biblioteca_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: biblioteca_digital
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: biblioteca_user
      MYSQL_PASSWORD: biblioteca_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - biblioteca_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: biblioteca_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - biblioteca_network

volumes:
  mysql_data:
    driver: local

networks:
  biblioteca_network:
    driver: bridge
